#Travis CI configuration for VXL
# See http://travis-ci.org/vxl/vxl

sudo: false

language: cpp
compiler:
  - gcc
  - clang

# https://docs.travis-ci.com/user/customizing-the-build/
git:
  depth: 3

#cache: false
#  directories:
#  - $HOME/deps

#before_script:
#  - bash .travis/install-deps.sh

#script:
#  - export PATH=$HOME/deps/bin:$PATH
script:
  - cmake --version
  - mkdir build
  - mkdir $HOME/install
  - cd build
  - cmake
          -DCMAKE_INSTALL_PREFIX=$HOME/install
          -DCMAKE_CXX_STANDARD=98
          ../
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalConfigure
  - ctest -D ExperimentalBuild -j2
  - ctest -D ExperimentalTest --schedule-random -j2
  - ctest -D ExperimentalSubmit
  - make install
